"""phone_postitoin_place_are_nullable

Revision ID: 326a9dff44f0
Revises: 8ef158a42d2a
Create Date: 2025-12-25 18:04:43.274840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326a9dff44f0'
down_revision: Union[str, Sequence[str], None] = '8ef158a42d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_comment='Phone number of the user')
    op.alter_column('users', 'position',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_comment='Position of the user')
    op.alter_column('users', 'place_of_work',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_comment='Place of work of the user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'place_of_work',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_comment='Place of work of the user')
    op.alter_column('users', 'position',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_comment='Position of the user')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_comment='Phone number of the user')
    # ### end Alembic commands ###
