"""create_model_for_reports

Revision ID: 44c67503bb96
Revises: 90f6a1996e9a
Create Date: 2026-01-12 18:34:47.023742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c67503bb96'
down_revision: Union[str, Sequence[str], None] = '90f6a1996e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Report name'),
    sa.Column('format', sa.Enum('PDF', 'EXCEL', name='reportformat'), nullable=False, comment='Report format (PDF or Excel)'),
    sa.Column('s3_key', sa.String(length=512), nullable=False, comment='S3 key for the report file'),
    sa.Column('created_by_id', sa.Integer(), nullable=False, comment='ID of the user who created the report'),
    sa.Column('period_start', sa.Date(), nullable=False, comment='Start date of the report period'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='End date of the report period'),
    sa.Column('total_requests', sa.Integer(), nullable=False, comment='Total number of requests at report creation time'),
    sa.Column('approved_requests', sa.Integer(), nullable=False, comment='Number of approved requests at report creation time'),
    sa.Column('denied_requests', sa.Integer(), nullable=False, comment='Number of denied requests at report creation time'),
    sa.Column('pending_requests', sa.Integer(), nullable=False, comment='Number of pending/submitted requests at report creation time'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
