"""create_ambulance_request_models

Revision ID: 4dc81045fd8d
Revises: f5a8b9c0d123
Create Date: 2025-12-08 23:40:51.511127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc81045fd8d'
down_revision: Union[str, Sequence[str], None] = 'f5a8b9c0d123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulance_requests',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user who created the request'),
    sa.Column('transportation_type', sa.Enum('AMBULANCE', name='transportationtype'), nullable=False, comment='Type of transportation'),
    sa.Column('patient_first_name', sa.String(length=100), nullable=False, comment='Patient first name'),
    sa.Column('patient_last_name', sa.String(length=100), nullable=False, comment='Patient last name'),
    sa.Column('patient_date_of_birth', sa.Date(), nullable=False, comment='Patient date of birth'),
    sa.Column('patient_id', sa.String(length=50), nullable=False, comment='Patient ID'),
    sa.Column('date_of_transport', sa.Date(), nullable=False, comment='Date of transport'),
    sa.Column('time_of_transport', sa.Time(), nullable=False, comment='Time of transport'),
    sa.Column('pickup_address', sa.String(length=500), nullable=False, comment='Pickup address'),
    sa.Column('destination_address', sa.String(length=500), nullable=False, comment='Destination address'),
    sa.Column('primary_diagnosis', sa.Text(), nullable=True, comment='Primary diagnosis (filled by AI)'),
    sa.Column('medical_justification', sa.Text(), nullable=True, comment='Medical justification (filled by AI)'),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'PROCESSING', 'DENIED', name='requeststatus'), server_default='PROCESSING', nullable=False, comment='Current status of the request'),
    sa.Column('form_number', sa.String(length=50), nullable=True, comment='CMS form number (e.g., CMS-10344)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_files',
    sa.Column('request_id', sa.Integer(), nullable=True, comment='ID of the ambulance request (nullable for temporary files)'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Original filename'),
    sa.Column('s3_key', sa.String(length=500), nullable=False, comment='S3 object key (path in S3 bucket)'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME type of the file'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['ambulance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_status_history',
    sa.Column('request_id', sa.Integer(), nullable=False, comment='ID of the ambulance request'),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'PROCESSING', 'DENIED', name='requeststatus'), nullable=False, comment='Status at this point in time'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes about the status change'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['ambulance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_status_history')
    op.drop_table('request_files')
    op.drop_table('ambulance_requests')
    # ### end Alembic commands ###
