"""add_phone_postion_place_of_work

Revision ID: 5c0c548ee4f2
Revises: 8ee69a09f0be
Create Date: 2025-12-23 18:19:08.729106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0c548ee4f2'
down_revision: Union[str, Sequence[str], None] = '8ee69a09f0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=16), nullable=False, comment='Phone number of the user'))
    op.add_column('users', sa.Column('position', sa.String(length=128), nullable=False, comment='Position of the user'))
    op.add_column('users', sa.Column('place_of_work', sa.String(length=128), nullable=False, comment='Place of work of the user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'place_of_work')
    op.drop_column('users', 'position')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
