"""added_expiration_date_field

Revision ID: 5e5c1bf3d723
Revises: 44c67503bb96
Create Date: 2026-01-20 15:14:15.305272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5c1bf3d723'
down_revision: Union[str, Sequence[str], None] = '44c67503bb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulance_requests', sa.Column('expiration_date', sa.Date(), nullable=True, comment='Prior authorization expiration date'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ambulance_requests', 'expiration_date')
    # ### end Alembic commands ###
