"""add_is_verified_for_token

Revision ID: 8ee69a09f0be
Revises: c86800d8acb2
Create Date: 2025-12-22 22:26:36.272474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee69a09f0be'
down_revision: Union[str, Sequence[str], None] = 'c86800d8acb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_codes', sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether the code has been verified'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_codes', 'is_verified')
    # ### end Alembic commands ###
