"""add_notification_title

Revision ID: 90f6a1996e9a
Revises: f49b4ed2ad4b
Create Date: 2026-01-08 20:56:26.280088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f6a1996e9a'
down_revision: Union[str, Sequence[str], None] = 'f49b4ed2ad4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(length=200), nullable=True, comment='Notification title/heading'))
    op.alter_column('notifications', 'request_id',
               existing_type=sa.INTEGER(),
               comment='ID of the related ambulance request (nullable for SYSTEM )',
               existing_comment='ID of the related ambulance request (nullable for SYSTEM notifications)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'request_id',
               existing_type=sa.INTEGER(),
               comment='ID of the related ambulance request (nullable for SYSTEM notifications)',
               existing_comment='ID of the related ambulance request (nullable for SYSTEM )',
               existing_nullable=True)
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
