"""create_orgaization_model

Revision ID: 943c86fc0c90
Revises: 769c041c5983
Create Date: 2026-01-06 17:42:10.473109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943c86fc0c90'
down_revision: Union[str, Sequence[str], None] = '769c041c5983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user this organization belongs to'),
    sa.Column('provider_type', sa.String(length=512), nullable=True, comment='Type of provider'),
    sa.Column('professional_id', sa.String(length=128), nullable=True, comment='Professional ID'),
    sa.Column('medic_name', sa.String(length=128), nullable=True, comment='Medic name'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    # ### end Alembic commands ###
