"""new_statuses

Revision ID: 9d0173bad9c8
Revises: d55d476a053e
Create Date: 2026-01-07 18:47:49.017566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0173bad9c8'
down_revision: Union[str, Sequence[str], None] = 'd55d476a053e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

denial_reason_enum = sa.Enum(
    'DUPLICATE_REQUEST',
    'INVALID_REQUEST_TYPE',
    'INVALID_DIAGNOSIS_CODE',
    'MISSING_PHYSICIAN_SIGNATURE',
    'TRANSPORT_LEVEL_NOT_MEDICALLY_NECESSARY',
    'INCOMPLETE_MEDICAL_DOCUMENTATION',
    'OUTDATED_OR_EXPIRED_DOCUMENTS',
    'INCORRECT_OR_INCONSISTENT_PATIENT_INFORMATION',
    'OTHER_REASON',
    name='denialreason'
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    denial_reason_enum.create(op.get_bind())
    op.add_column('ambulance_requests', sa.Column(
        'denial_reason',
        denial_reason_enum,
        nullable=True,
        comment='Reason for denial if request was denied'
    ))
    op.add_column('ambulance_requests', sa.Column(
        'denial_notes',
        sa.String(length=256),
        nullable=True,
        comment='Additional notes for denial (required if denial_reason is OTHER_REASON)'
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ambulance_requests', 'denial_notes')
    op.drop_column('ambulance_requests', 'denial_reason')
    denial_reason_enum.drop(op.get_bind())
    # ### end Alembic commands ###
