"""add_reviewer_id_field

Revision ID: c86800d8acb2
Revises: 4dc81045fd8d
Create Date: 2025-12-11 23:33:59.902370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86800d8acb2'
down_revision: Union[str, Sequence[str], None] = '4dc81045fd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambulance_requests', sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='ID of the reviewer (provider) who set the request status'))
    op.create_foreign_key(None, 'ambulance_requests', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ambulance_requests', type_='foreignkey')
    op.drop_column('ambulance_requests', 'reviewer_id')
    # ### end Alembic commands ###
