"""created_user_model

Revision ID: e09128458119
Revises: c6c0bb3399f0
Create Date: 2025-11-25 19:11:18.627072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09128458119'
down_revision: Union[str, Sequence[str], None] = 'c6c0bb3399f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=32), nullable=False, comment='First name of the user'),
    sa.Column('surname', sa.String(length=32), nullable=False, comment='Last name of the user'),
    sa.Column('email', sa.String(length=254), nullable=False, comment='Unique email address for login'),
    sa.Column('password', sa.String(length=512), nullable=False, comment='Hashed password'),
    sa.Column('role', sa.Enum('ADMIN', 'PROVIDER', name='userrole'), server_default='PROVIDER', nullable=False, comment='Role of the user: admin or provider'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Indicates if the instance is active'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
