"""create_notification_model

Revision ID: f49b4ed2ad4b
Revises: 5b953111983c
Create Date: 2026-01-08 18:00:03.405628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49b4ed2ad4b'
down_revision: Union[str, Sequence[str], None] = '5b953111983c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID of the user who receives the notification'),
    sa.Column('category', sa.Enum('STATUS_UPDATE', 'DOCUMENT', 'REQUIREMENT', 'SYSTEM', name='notificationcategory'), nullable=False, comment='Category of the notification'),
    sa.Column('message', sa.Text(), nullable=False, comment='Notification message text'),
    sa.Column('request_id', sa.Integer(), nullable=True, comment='ID of the related ambulance request (nullable for SYSTEM notifications)'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Whether the notification has been read'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['ambulance_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
