"""password_reset_code_model

Revision ID: f5a8b9c0d123
Revises: d4c7c0aaa331
Create Date: 2025-01-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a8b9c0d123'
down_revision: Union[str, Sequence[str], None] = 'd4c7c0aaa331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'password_reset_codes',
        sa.Column(
            'code',
            sa.String(length=5),
            nullable=False,
            comment='5-digit password reset code',
        ),
        sa.Column(
            'user_id',
            sa.Integer(),
            nullable=False,
            comment='User ID associated with the reset code',
        ),
        sa.Column(
            'expires_at',
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            comment='Code expiration timestamp',
        ),
        sa.Column(
            'is_used',
            sa.Boolean(),
            nullable=False,
            server_default='false',
            comment='Whether the code has been used',
        ),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_password_reset_codes_code'),
        'password_reset_codes',
        ['code'],
        unique=False,
    )
    op.create_index(
        op.f('ix_password_reset_codes_expires_at'),
        'password_reset_codes',
        ['expires_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_password_reset_codes_user_id'),
        'password_reset_codes',
        ['user_id'],
        unique=False,
    )
    op.create_index(
        'ix_password_reset_codes_user_id_expires_at',
        'password_reset_codes',
        ['user_id', 'expires_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_password_reset_codes_user_id_expires_at',
        table_name='password_reset_codes',
    )
    op.drop_index(
        op.f('ix_password_reset_codes_user_id'),
        table_name='password_reset_codes',
    )
    op.drop_index(
        op.f('ix_password_reset_codes_expires_at'),
        table_name='password_reset_codes',
    )
    op.drop_index(
        op.f('ix_password_reset_codes_code'), table_name='password_reset_codes'
    )
    op.drop_table('password_reset_codes')
    # ### end Alembic commands ###
