import { type ColumnDef } from '@tanstack/react-table';
import { format } from 'date-fns';
import { Download } from 'lucide-react';

import { TableHeadCell } from '@/shared/components';
import { cn } from '@/shared/lib/utils';

import { type IRecentReport, type IMetric } from './types';

export const metricColumns: ColumnDef<IMetric>[] = [
  {
    accessorKey: 'metric',
    header: () => <TableHeadCell className='text-sm'>Metric</TableHeadCell>,
    cell: ({ getValue }) => (
      <span className='text-brand-dark text-xs font-bold md:text-sm'>
        {getValue<string>()}
      </span>
    ),
  },
  {
    accessorKey: 'value',
    header: () => <TableHeadCell className='text-sm'>Value</TableHeadCell>,
    cell: ({ getValue }) => (
      <span className='text-brand-dark text-xs font-bold md:text-sm'>
        {getValue<string>()}
      </span>
    ),
  },
  {
    accessorKey: 'change',
    header: () => <TableHeadCell className='text-sm'>Change</TableHeadCell>,
    cell: ({ getValue }) => {
      const changeRate = getValue<number>();

      return (
        <span
          className={cn('text-sm', {
            'text-status-destructive': changeRate < 0,
            'text-status-success': changeRate > 0,
            'text-status-info': changeRate === 0,
          })}
        >
          {Math.round(changeRate)}
        </span>
      );
    },
  },
];

export const reportsColumns: ColumnDef<IRecentReport>[] = [
  {
    accessorKey: 'name',
    header: () => <TableHeadCell className='text-sm'>Name</TableHeadCell>,
  },
  {
    accessorKey: 'generatedBy',
    header: () => (
      <TableHeadCell className='text-sm'>Generated by</TableHeadCell>
    ),
    cell: ({ getValue }) => (
      <span className='font-bold text-black'>{getValue<string>()}</span>
    ),
  },
  {
    accessorKey: 'format',
    header: () => <TableHeadCell className='text-sm'>Format</TableHeadCell>,
    cell: ({ getValue }) => (
      <span className='font-bold text-black'>{getValue<string>()}</span>
    ),
  },
  {
    accessorKey: 'date',
    header: () => <TableHeadCell className='text-sm'>Date</TableHeadCell>,
    cell: ({ getValue }) => {
      const formattedDate = format(new Date(getValue<string>()), 'MM/dd/yyyy');

      return <time dateTime={formattedDate}>{formattedDate}</time>;
    },
  },

  {
    id: 'action',
    accessorKey: 'link',
    header: () => <TableHeadCell className='text-sm'>Action</TableHeadCell>,
    cell: ({ getValue }) => (
      <a
        href={getValue<string>()}
        className='text-accent-foreground pointer-events-none flex cursor-not-allowed items-center gap-2'
        download
      >
        <Download className='text-status-info size-5' />
        <span>Download</span>
      </a>
    ),
  },
];
